version: '3.8'

services:
  app:
    container_name: nigeria-uni
    image: nigeria-uni
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - "8000:8000"