package models

type Universities struct{
	Name string `json:"name"`
	Abbrv string `json:"abbreviation"`
	WebsiteLink string `json:"websitelink"`
}

func Uni() []*Universities {
	return []*Universities{
		&Universities{Name: "Abia State University, Uturu", Abbrv: "absu", WebsiteLink: "https://abiastateuniversity.edu.ng/"},
		&Universities{Name: "Achievers University, Owo", Abbrv: "auo", WebsiteLink: "https://www.achievers.edu.ng/"},
		&Universities{Name: "Adamawa State University", Abbrv: "adsu", WebsiteLink: "https://adsu.edu.ng/"},
		&Universities{Name: "Adekunle Ajasin University", Abbrv: "aaua", WebsiteLink: "https://aaua.edu.ng/"},
		&Universities{Name: "Adeleke University, Ede", Abbrv: "aue", WebsiteLink: "https://adelekeuniversity.edu.ng/"},
		&Universities{Name: "Admiralty University of Nigeria", Abbrv: "adun", WebsiteLink: "https://adun.edu.ng/"},
		&Universities{Name: "Afe Babalola University", Abbrv: "abuad", WebsiteLink: "https://www.abuad.edu.ng/"},
		&Universities{Name: "African Univeristy of Science and Technology", Abbrv: "aust", WebsiteLink: "https://aust.edu.ng/"},
		&Universities{Name: "Ahmadu Bello University, Zaria", Abbrv: "abuzaria", WebsiteLink: "https://www.abu.edu.ng/"},
		&Universities{Name: "Ajayi Crowther University", Abbrv: "acu", WebsiteLink: "https://acu.edu.ng/"},
		&Universities{Name: "Akwa Ibom State University", Abbrv: "aksu", WebsiteLink: "https://aksu.edu.ng/newsite/"},
		&Universities{Name: "Alex Ekwueme Federal University, Ndufu-Alike", Abbrv: "funai", WebsiteLink: "https://funai.edu.ng/"},
		&Universities{Name: "Al-Hikmah University", Abbrv: "hui", WebsiteLink: "https://alhikmahuniversity.edu.ng/"},
		&Universities{Name: "Al-Qalam University, Katsina", Abbrv: "auk", WebsiteLink: "https://auk.edu.ng/"},
		&Universities{Name: "Ambrose Alli University", Abbrv: "aau", WebsiteLink: "https://www.aauekpoma.edu.ng/"},
		&Universities{Name: "American University of Nigeria", Abbrv: "aun", WebsiteLink: "https://www.aun.edu.ng/"},
		&Universities{Name: "Anchor University, Lagos", Abbrv: "aul", WebsiteLink: "https://aul.edu.ng/"},
		&Universities{Name: "Arthur Jarvis University", Abbrv: "aju", WebsiteLink: "https://arthurjarvisuniversity.edu.ng/"},
		&Universities{Name: "Atiba University", Abbrv: "atu", WebsiteLink: "https://www.atibauniversity.edu.ng/"},
		&Universities{Name: "Augustine University", Abbrv: "aui", WebsiteLink: "https://augustineuniversity.edu.ng/"},
		&Universities{Name: "Babcock University", Abbrv: "bu", WebsiteLink: "https://www.babcock.edu.ng/"},
		&Universities{Name: "Bauchi State University", Abbrv: "basug", WebsiteLink: "Bauchi State University"},
		&Universities{Name: "Bayero University Kano", Abbrv: "buk", WebsiteLink: "https://www.buk.edu.ng/"},
		&Universities{Name: "Baze University", Abbrv: "baze", WebsiteLink: "https://www.bazeuniversity.edu.ng/"},
		&Universities{Name: "Bells University of Technology", Abbrv: "bellstech", WebsiteLink: "https://www.bellsuniversity.edu.ng/"},
		&Universities{Name: "Benson Idahosa University", Abbrv: "biu", WebsiteLink: "https://www.biu.edu.ng/"},
		&Universities{Name: "Benue State University", Abbrv: "bsum", WebsiteLink: "https://www.bsum.edu.ng/"},
		&Universities{Name: "Bingham University", Abbrv: "bu", WebsiteLink: "https://binghamuni.edu.ng/v2/"},
		&Universities{Name: "Borno State University", Abbrv: "bosu", WebsiteLink: "https://bosu.edu.ng/"},
		&Universities{Name: "Bowen University", Abbrv: "bowen", WebsiteLink: "https://bowen.edu.ng/"},
		&Universities{Name: "Caleb University", Abbrv: "cul", WebsiteLink: "https://calebuniversity.edu.ng/"},
		&Universities{Name: "Caritas Univeristy", Abbrv: "cua", WebsiteLink: "https://www.caritasuni.edu.ng/"},
		&Universities{Name: "Chrisland University", Abbrv: "chrislanf", WebsiteLink: "https://www.chrislanduniversity.edu.ng/"},
		&Universities{Name: "Christopher University", Abbrv: "unichris", WebsiteLink: "https://christopheruniversity.edu.ng/"},
		&Universities{Name: "Chukwuemeka Odumegwu Ojukwu University", Abbrv: "coou", WebsiteLink: "https://coou.edu.ng/"},
		&Universities{Name: "Clifford University", Abbrv: "clu", WebsiteLink: "https://clifforduni.edu.ng/"},
		&Universities{Name: "Coal City University", Abbrv: "ccu", WebsiteLink: "https://ccu.edu.ng/"},
		&Universities{Name: "Convenant University", Abbrv: "cu", WebsiteLink: "https://www.covenantuniversity.edu.ng/"},
		&Universities{Name: "Crawford University", Abbrv: "cru", WebsiteLink: "http://crawforduniversity.edu.ng/crawford/"},
		&Universities{Name: "Crescent University, Abeokuta", Abbrv: "cuab", WebsiteLink: ""},
		&Universities{Name: "Cross River University of Technology", Abbrv: "crutech", WebsiteLink: "https://www.crutech.edu.ng/"},
		&Universities{Name: "Crown Hill University", Abbrv: "chu", WebsiteLink: "https://crownhilluniversity.edu.ng/"},
		&Universities{Name: "Delta State University, Abraka", Abbrv: "delsu", WebsiteLink: "https://www.delsu.edu.ng/"},
		&Universities{Name: "Dominican University, Ibadan", Abbrv: "dui", WebsiteLink: "https://dui.edu.ng/"},
		&Universities{Name: "Eastern Palm University", Abbrv: "epu", WebsiteLink: "https://epu.edu.ng/"},
		&Universities{Name: "Ebonyi State University", Abbrv: "ebsu", WebsiteLink: "https://ebsu.edu.ng/"},
		&Universities{Name: "Edo State University, Iyamho", Abbrv: "edsu", WebsiteLink: "https://www.edouniversity.edu.ng/"},
		&Universities{Name: "Edwin Clark University", Abbrv: "ecu", WebsiteLink: "http://edwinclarkuniversity.edu.ng/"},
		&Universities{Name: "Ekiti State University, Ado Ekiti", Abbrv: "eksu", WebsiteLink: "Ekiti State University, Ado Ekiti"},
		&Universities{Name: "Eko University of Medical and Health Sciences", Abbrv: "ekounimed", WebsiteLink: "https://ekounimed.edu.ng/"},
		&Universities{Name: "Elizade University", Abbrv: "eui", WebsiteLink: "https://www.elizadeuniversity.edu.ng/"},
		&Universities{Name: "Enugu State University of Science and Technology", Abbrv: "esut", WebsiteLink: ""},
		&Universities{Name: "Evangel University, Akaeze", Abbrv: "eua", WebsiteLink: "https://evangeluniversity.edu.ng/"},
		&Universities{Name: "Federal University of Agriculture, Abeokuta", Abbrv: "funnab", WebsiteLink: "https://unaab.edu.ng/"},
		&Universities{Name: "Federal University of Petroleum Resources", Abbrv: "fupre", WebsiteLink: "https://www.fupre.edu.ng/"},
		&Universities{Name: "Federal University of Technology, Akure", Abbrv: "futa", WebsiteLink: "https://www.futa.edu.ng/"},
		&Universities{Name: "Federal University of Technology, Minna", Abbrv: "futminna", WebsiteLink: "https://futminna.edu.ng/"},
		&Universities{Name: "Federal University of Technology, Owerri", Abbrv: "futo", WebsiteLink: "https://futo.edu.ng/"},
		&Universities{Name: "Federal University, Birnin Kebbi", Abbrv: "fubk", WebsiteLink: "https://fubk.edu.ng/"},
		&Universities{Name: "Federal University, Dutse", Abbrv: "fud", WebsiteLink: "https://fud.edu.ng/"},
		&Universities{Name: "Federal University, Dutsin-Ma", Abbrv: "fudma", WebsiteLink: "https://www.fudutsinma.edu.ng/Federal University, Gashua"},
		&Universities{Name: "Federal University, Gashua", Abbrv: "fuga", WebsiteLink: "https://www.fugashua.edu.ng/"},
		&Universities{Name: "Federal University, Gusau", Abbrv: "fugus", WebsiteLink: ""},
		&Universities{Name: "Federal University, Kashere", Abbrv: "fuk", WebsiteLink: ""},
		&Universities{Name: "Federal University, Lafia", Abbrv: "fulafia", WebsiteLink: ""},
		&Universities{Name: "Federal University, Lokoja", Abbrv: "ful", WebsiteLink: ""},
		&Universities{Name: "Federal University, Otuoke", Abbrv: "fuotuoke", WebsiteLink: ""},
		&Universities{Name: "Federal University, Oye-Ekiti", Abbrv: "fuoye", WebsiteLink: ""},
		&Universities{Name: "Federal University, Wukari", Abbrv: "fuwukari", WebsiteLink: ""},
		&Universities{Name: "Fountain University, Osogbo", Abbrv: "fuo", WebsiteLink: ""},
		&Universities{Name: "Glorious Vision University", Abbrv: "gvu", WebsiteLink: ""},
		&Universities{Name: "Godfrey Okoye University", Abbrv: "gou", WebsiteLink: ""},
		&Universities{Name: "Gombe State University", Abbrv: "gsu", WebsiteLink: ""},
		&Universities{Name: "Gombe State University of Science and Technology", Abbrv: "gsust", WebsiteLink: ""},
		&Universities{Name: "Gregory University, Uturu", Abbrv: "guu", WebsiteLink: ""},
		&Universities{Name: "Hallmark University, Ijebu-Itele", Abbrv: "hallmark", WebsiteLink: ""},
		&Universities{Name: "Hezekiah University", Abbrv: "hu", WebsiteLink: ""},
		&Universities{Name: "Ibrahim Badamasi Babangida University", Abbrv: "ibbul", WebsiteLink: ""},
		&Universities{Name: "Igbinedion University Okada", Abbrv: "iuo", WebsiteLink: ""},
		&Universities{Name: "Ignatius Ajuru University of Education", Abbrv: "iaue", WebsiteLink: ""},
		&Universities{Name: "Imo State University", Abbrv: "imsu", WebsiteLink: ""},
		&Universities{Name: "Joseph Ayo Babalola University", Abbrv: "jabu", WebsiteLink: ""},
		&Universities{Name: "Kaduna State University", Abbrv: "kasu", WebsiteLink: ""},
		&Universities{Name: "Kano University of Science and Technology'", Abbrv: "kust", WebsiteLink: ""},
		&Universities{Name: "Kebbi State University of Science and Technology", Abbrv: "ksusta", WebsiteLink: ""},
		&Universities{Name: "Kings University", Abbrv: "ku", WebsiteLink: ""},
		&Universities{Name: "Kogi State University", Abbrv: "ksu", WebsiteLink: ""},
		&Universities{Name: "Kola Daisi University", Abbrv: "kdu", WebsiteLink: ""},
		&Universities{Name: "Kwara State University", Abbrv: "kwasu", WebsiteLink: ""},
		&Universities{Name: "Kwararafa University, Wukari", Abbrv: "kwu", WebsiteLink: ""},
		&Universities{Name: "Ladoke Akintola University of Technology", Abbrv: "lautech", WebsiteLink: ""},
		&Universities{Name: "Lagos State University", Abbrv: "lasu", WebsiteLink: ""},
		&Universities{Name: "Landmark University", Abbrv: "lmu", WebsiteLink: ""},
		&Universities{Name: "Lead City University", Abbrv: "lcu", WebsiteLink: ""},
		&Universities{Name: "Legacy University, Okija", Abbrv: "luo", WebsiteLink: ""},
		&Universities{Name: "Madonna University, Okija", Abbrv: "muo", WebsiteLink: ""},
		&Universities{Name: "Mcpherson University", Abbrv: "McU", WebsiteLink: ""},
		&Universities{Name: "Michael and Cecilia Ibru University", Abbrv: "mciu", WebsiteLink: ""},
		&Universities{Name: "Michael Okpara University of Agriculture", Abbrv: "mouau", WebsiteLink: ""},
		&Universities{Name: "Modibbo Adama University of Technology", Abbrv: "mautech", WebsiteLink: ""},
		&Universities{Name: "Moshood Abiola University of Science and Technology, Abeokuta", Abbrv: "maustech", WebsiteLink: ""},
		&Universities{Name: "Mountain Top University", Abbrv: "mtu", WebsiteLink: ""},
		&Universities{Name: "Nasarawa State University", Abbrv: "nsuk", WebsiteLink: ""},
		&Universities{Name: "Niger Delta University", Abbrv: "ndu", WebsiteLink: ""},
		&Universities{Name: "Nigerian Maritime University, Okerenkoko", Abbrv: "nmu", WebsiteLink: ""},
		&Universities{Name: "Nile University of Nigeria", Abbrv: "nile", WebsiteLink: ""},
		&Universities{Name: "Nnamdi Azikiwe University", Abbrv: "unizik", WebsiteLink: ""},
		&Universities{Name: "Novena University", Abbrv: "novena", WebsiteLink: ""},
		&Universities{Name: "Obafemi Awolowo University", Abbrv: "oau", WebsiteLink: ""},
		&Universities{Name: "Obong University", Abbrv: "ouo", WebsiteLink: ""},
		&Universities{Name: "Oduduwa University", Abbrv: "oui", WebsiteLink: ""},
		&Universities{Name: "Olabisi Onabanjo University", Abbrv: "oou", WebsiteLink: ""},
		&Universities{Name: "Ondo State University of Science and Technology", Abbrv: "osutech", WebsiteLink: ""},
		&Universities{Name: "PAMO University of Medical Sciences", Abbrv: "pums", WebsiteLink: ""},
		&Universities{Name: "Pan-Atlantic University", Abbrv: "pau", WebsiteLink: ""},
		&Universities{Name: "Paul University", Abbrv: "pua", WebsiteLink: ""},
		&Universities{Name: "Plateau State University", Abbrv: "plasu", WebsiteLink: ""},
		&Universities{Name: "Precious Cornerstone University", Abbrv: "pcu", WebsiteLink: ""},
		&Universities{Name: "Redeemer's University", Abbrv: "run", WebsiteLink: ""},
		&Universities{Name: "Renaissance University", Abbrv: "rue", WebsiteLink: ""},
		&Universities{Name: "Rhema University", Abbrv: "ru", WebsiteLink: ""},
		&Universities{Name: "Ritman University", Abbrv: "ru", WebsiteLink: ""},
		&Universities{Name: "Rivers State University", Abbrv: "rsu", WebsiteLink: ""},
		&Universities{Name: "Salem University", Abbrv: "su", WebsiteLink: ""},
		&Universities{Name: "Skyline University Nigeria", Abbrv: "sun", WebsiteLink: ""},
		&Universities{Name: "Sokoto State University", Abbrv: "ssu", WebsiteLink: ""},
		&Universities{Name: "Southwestern University, Nigeria", Abbrv: "sun", WebsiteLink: ""},
		&Universities{Name: "Spiritan University, Nneochi", Abbrv: "sun", WebsiteLink: ""},
		&Universities{Name: "Sule Lamido University", Abbrv: "slu", WebsiteLink: ""},
		&Universities{Name: "Summit University Offa", Abbrv: "suo", WebsiteLink: ""},
		&Universities{Name: "Tai Solarin University of Education", Abbrv: "tasued", WebsiteLink: ""},
		&Universities{Name: "Tansian University", Abbrv: "tanu", WebsiteLink: ""},
		&Universities{Name: "Taraba State University", Abbrv: "tsu", WebsiteLink: ""},
		&Universities{Name: "The Technical University", Abbrv: "ttu", WebsiteLink: ""},
		&Universities{Name: "Umaru Musa Yar'Adua University", Abbrv: "umyu", WebsiteLink: ""},
		&Universities{Name: "University of Abuja", Abbrv: "uniabuja", WebsiteLink: ""},
		&Universities{Name: "University of Africa", Abbrv: "uoa", WebsiteLink: ""},
		&Universities{Name: "University of Agriculture, Makurdi", Abbrv: "uam", WebsiteLink: ""},
		&Universities{Name: "University of Benin", Abbrv: "uniben", WebsiteLink: ""},
		&Universities{Name: "", Abbrv: "", WebsiteLink: ""},
		&Universities{Name: "", Abbrv: "", WebsiteLink: ""},
		&Universities{Name: "", Abbrv: "", WebsiteLink: ""},
		&Universities{Name: "", Abbrv: "", WebsiteLink: ""},
		&Universities{Name: "", Abbrv: "", WebsiteLink: ""},
	}
}